apiVersion: v1
kind: Service
metadata: 
  name: platforms-np-svc
spec: 
  type: NodePort
  selector: 
    app: platformservice
  ports: 
    - name: platform-service-port 
      port: 80 
      protocol: TCP 
      targetPort: 80 